### ISSUE TITLE
Problem with TypeBugs (airflow)

### ISSUE THREAD

**Issue by gsakkas** [kupl/PyTER#1]
Hello,

I have a couple of problems with running different tests in the TypeBugs benchmark. For example when I try to run `airflow/airflow-14513`, installing all the `requirements.txt` and doing `bash dependency_test.sh` seems to work fine, but when I run `pytest` I get
```
  ...
  File "/home/gsakkas/anaconda3/envs/venv-3.6.9/lib/python3.6/site-packages/_pytest/config/argparsing.py", line 369, in addoption
    raise ValueError("option names %s already added" % conflict)
ValueError: option names {'--from-filenames'} already added
```

Any work-arounds or ideas on that?

Thanks,
George

**Comment by gsakkas** [comment]
It seems that `pyparsing==2.4.7` is needed in `requirements.txt` instead of `pyparsing==3.0.9`!

**Comment by marinelay** [comment]
I'm sorry about the delay.
Thanks for your interest!
